# -------------------------------
# Configuration
# -------------------------------

# exa
export EXA_COLORS="da=1;35"

# -------------------------------
# Aliases
# -------------------------------

alias vim="nvim"

# exa
alias ll="exa -lh"
alias la="exa -lah"

# -------------------------------
# Miscellaneous
# -------------------------------

export PATH="$PATH:$HOME/.config/scripts"
